name: Compile and push server image for staging

on:
  pull_request:
    branches: ["dev"]
    types: ["closed"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx

      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_BACK_STAGING }}:latest

  deployment:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy stage
        run: |
          curl -X GET "https://ops.hamilton4.wns.wilders.dev/hooks/update"
